export const ADDINGREDIENT = 'ADDINGREDIENT';
export const REMOVEINGREDIENT = 'REMOVEINGREDIENT';
export const UPDATEORDER = 'UPDATEORDER';


export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENTS_ERROR';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUHT_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SETAUTHPATH = 'SETAUTHPATH';
export const PERSISTANTAUTH = 'PERSISTANTAUTH';
